version: "3.0"
services:
  rasa:
    image: rasa/rasa:3.6.21
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
      - -m
      - /app/models
      - --enable-api
      - --cors
      - "*"
      - --debug
      - --endpoints
      - endpoints.yml

  action_server:
    image: rasa/rasa-sdk:3.6.2
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command:
      - run
      - actions
